### ISSUE TITLE
Training data for decoder/encoder

### ISSUE THREAD

**Issue by PhysicsOfAI** [genforce/lia#1]
Hi,
It's not clear if the same training/testing data can be used for decoder and encoder training. Decoder training is exactly the same as StyleGAN as described. This stage can use the 9 ffhq tfrecords from StyleGAN having a resolution of 1024x1024. The encoder training seems to using a data set of resolution 128x128. Where is the data set?

**Comment by zhujiapeng** [comment]
Actually, it is the best choice to use the same training/testing dataset for training decoder and encoder, e.g. using FFHQ to training both decoder and encoder. In our paper, we just do the experiments on 128x128 image size. If you want to do experiments on a larger resolution dataset, just add its path to `Data_dir()`.
